# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: "Bug fixes :bug:"
      labels:
        - bug
        - regression
    - title: "🖧 P2P area"
      labels:
         - area/p2p
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
        - ux
        - roadmap
    - title: 🧠 Models
      labels:
        - area/ai-model
    - title: 📖 Documentation and examples
      labels:
        - kind/documentation
        - examples
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
